services:
  app:
    build:
      context: ./docker/php
    container_name: crm_testtask
    working_dir: /crm
    volumes:
      - ./src:/crm
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: crm_testtask-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/crm
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: crm_testtask_sql
    environment:
      MYSQL_DATABASE: crm_testtask
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/crm/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    depends_on:
      - mysql

  node:
    image: node:20
    container_name: crm_node
    working_dir: /crm
    volumes:
      - ./src:/crm

volumes:
  mysql_data: